### ISSUE TITLE
On GitLab, drawio-export ends up in error at the end of its run

### ISSUE THREAD

**Issue by rlespinasse** [rlespinasse/drawio-export#83]
This `gitlab-ci.yml` file

```yaml
drawio:
  stage: build
  image: 
    name: rlespinasse/drawio-export
    entrypoint: [""]
  script: 
    - /opt/drawio-desktop/entrypoint.sh
```

Will produce a failing job

> ERROR: Job failed: exit code 1

**Comment by Paxilein** [comment]
It's not only on GitLab... I encounter the same issue on Azure Devops, too...

##[error]Bash exited with code '1'.

**Comment by rlespinasse** [comment]
@Paxilein Can you have some code snippets to share to see how you use it?

**Comment by Paxilein** [comment]
This is the step in our Yaml Pipeline that exits with code 1 after it goes through both drawio-files in the directory :

```yaml
  - task: Bash@3
    displayName: "export drawio to PDF"
    inputs:
      workingDirectory: $(System.DefaultWorkingDirectory)/docs/assets
      targetType: inline
      script: |
          docker run -v $(pwd):/data rlespinasse/drawio-export --width 1000 --crop
```
